version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
      - ./node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - red-gestion-pagos

networks:
  red-gestion-pagos:
    external: true
